//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vidly.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwRental
    {
        public string Genre { get; set; }
        public Nullable<int> Id { get; set; }
        public int MovieId { get; set; }
        public string CustomerName { get; set; }
        public string MovieName { get; set; }
    }
}
